Hack-169 JaCoCo Test Coverage Summary on GitHub PR

diff --git a/.github/workflows/gh-actions-build-app-workflow.yml b/.github/workflows/gh-actions-build-app-workflow.yml
--- a/.github/workflows/gh-actions-build-app-workflow.yml
+++ b/.github/workflows/gh-actions-build-app-workflow.yml
@@ -48,41 +48,7 @@ jobs:
           echo "COVERAGE=$(echo $GH_COVERAGE*100 | bc)" >> $GITHUB_ENV
           echo "BRANCH_COVERAGE=$(echo $GH_BRANCH_COVERAGE*100 | bc)" >> $GITHUB_ENV
           
-    - name: Log coverage percentage
-      run: |
-        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
-        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
-        echo "HEDO-1 [$COVERAGE]"
-        echo "HEDO-1 [$BRANCH_COVERAGE]"
-        echo "HEDO-2 ${{ env.COVERAGE }}"
-        echo "HEDO-2 ${{ env.BRANCH_COVERAGE }}"
-        echo "COVERAGE_ROUNDED=$(echo $COVERAGE | awk '{printf("%d\n",$1 + 0.5)}')"  >> $GITHUB_ENV 
-        echo "BRANCH_COVERAGE_ROUNDED=$(echo $BRANCH_COVERAGE | awk '{printf("%d\n",$1 + 0.5)}')"  >> $GITHUB_ENV
-           
-    - name: Comment coverage statistics on Pull Requet(PR)        
-      uses: actions/github-script@v6
-      with:
-        script: |
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: '## JaCoCo Test Coverage Summary <br>\n * __Coverage:__ ${{ env.COVERAGE_ROUNDED }} % <br>\n * __Branches:__ ${{ env.BRANCH_COVERAGE_ROUNDED }} %'
-            })
-            
-    - name: 'Check Coverate Minimum Thresold, FAIL the workflow if below Thresold'
-      run: |
-           echo "Success! ${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}"
-           echo "Success! ${{ env.COVERAGE }}"
-           echo "Success! ${{ env.BRANCH_COVERAGE }}"
-           if [[ $(echo "$COVERAGE <= 80.00" | bc -l) -eq 1 ]]; then
-              echo "Coverage $COVERAGE is less than 80%, We must fail here."
-              exit 1
-           fi  
-           
-    - name: 'Read JACOCO File - Ignore Me'
-      run: |
-           echo "Try reading file."
+                     echo "Try reading file."
            echo "${PWD}"
            echo "$(cat ./target/site/jacoco/jacoco.csv)"
            
@@ -113,6 +79,39 @@ jobs:
             done < './target/site/jacoco/jacoco.csv'
             
             echo "GITHUB_COMMENT_FINAL=$github_comment" >> $GITHUB_ENV
+
+          
+    - name: Log coverage percentage
+      run: |
+        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
+        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
+        echo "HEDO-1 [$COVERAGE]"
+        echo "HEDO-1 [$BRANCH_COVERAGE]"
+        echo "HEDO-2 ${{ env.COVERAGE }}"
+        echo "HEDO-2 ${{ env.BRANCH_COVERAGE }}"
+        echo "COVERAGE_ROUNDED=$(echo $COVERAGE | awk '{printf("%d\n",$1 + 0.5)}')"  >> $GITHUB_ENV 
+        echo "BRANCH_COVERAGE_ROUNDED=$(echo $BRANCH_COVERAGE | awk '{printf("%d\n",$1 + 0.5)}')"  >> $GITHUB_ENV
+           
+    - name: Comment coverage statistics on Pull Requet(PR)        
+      uses: actions/github-script@v6
+      with:
+        script: |
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: '## JaCoCo Test Coverage Summary <br>\n * __Coverage:__ ${{ env.COVERAGE_ROUNDED }} % <br>\n * __Branches:__ ${{ env.BRANCH_COVERAGE_ROUNDED }} \n\n  ${{ env.GITHUB_COMMENT_FINAL }} %'
+            })
+            
+    - name: 'Check Coverate Minimum Thresold, FAIL the workflow if below Thresold'
+      run: |
+           echo "Success! ${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}"
+           echo "Success! ${{ env.COVERAGE }}"
+           echo "Success! ${{ env.BRANCH_COVERAGE }}"
+           if [[ $(echo "$COVERAGE <= 80.00" | bc -l) -eq 1 ]]; then
+              echo "Coverage $COVERAGE is less than 80%, We must fail here."
+              exit 1
+           fi  
             
     - name: 'GitHub HTML Markup Comment - FINAL'
       run: |
